module SkelVhdl where

-- Haskell module generated by the BNF converter

import AbsVhdl
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transNumString :: NumString -> Result
transNumString x = case x of
  NumString string -> failure x
transIS :: IS -> Result
transIS x = case x of
  IS -> failure x
transBUSText :: BUSText -> Result
transBUSText x = case x of
  BUSText -> failure x
transGUARDEDtext :: GUARDEDtext -> Result
transGUARDEDtext x = case x of
  GUARDEDtext -> failure x
transConstantText :: ConstantText -> Result
transConstantText x = case x of
  ConstantText -> failure x
transInText :: InText -> Result
transInText x = case x of
  InText -> failure x
transSIGNALText :: SIGNALText -> Result
transSIGNALText x = case x of
  SIGNALText -> failure x
transVARIABLEText :: VARIABLEText -> Result
transVARIABLEText x = case x of
  VARIABLEText -> failure x
transPackageBodytext :: PackageBodytext -> Result
transPackageBodytext x = case x of
  PackageBodytext -> failure x
transAbstract_literal :: Abstract_literal -> Result
transAbstract_literal x = case x of
  Abstract_literalDecimal_literal decimalliteral -> failure x
  Abstract_literalBased_literal basedliteral -> failure x
transAccess_type_definition :: Access_type_definition -> Result
transAccess_type_definition x = case x of
  Access_type_definition subtypeindication -> failure x
transVariable_name :: Variable_name -> Result
transVariable_name x = case x of
  Variable_name name -> failure x
transActual_designator :: Actual_designator -> Result
transActual_designator x = case x of
  Actual_designatorExpression expression -> failure x
  Actual_designatorSignal_name signalname -> failure x
  Actual_designatorVariable_name variablename -> failure x
  Actual_designatorFile_name filename -> failure x
  Actual_designator_OPEN -> failure x
transFile_name :: File_name -> Result
transFile_name x = case x of
  File_name name -> failure x
transActual_parameter_part :: Actual_parameter_part -> Result
transActual_parameter_part x = case x of
  Actual_parameter_part parameterassociationlist -> failure x
transParameter_association_list :: Parameter_association_list -> Result
transParameter_association_list x = case x of
  Parameter_association_list associationlist -> failure x
transActual_part :: Actual_part -> Result
transActual_part x = case x of
  Actual_partActual_designator actualdesignator -> failure x
  Actual_part1 functionname actualdesignator -> failure x
  Actual_part2 typemark actualdesignator -> failure x
transAdding_operator :: Adding_operator -> Result
transAdding_operator x = case x of
  Adding_operator1 -> failure x
  Adding_operator2 -> failure x
  Adding_operator3 -> failure x
transAggregate :: Aggregate -> Result
transAggregate x = case x of
  Aggregate elementassociations -> failure x
transAlias_declaration :: Alias_declaration -> Result
transAlias_declaration x = case x of
  Alias_declaration aliasdesignator subtypeindications name signatures -> failure x
transAlias_designator :: Alias_designator -> Result
transAlias_designator x = case x of
  Alias_designatorIdentifier identifier -> failure x
  Alias_designatorCharacter_literal characterliteral -> failure x
  Alias_designatorOperator_symbol operatorsymbol -> failure x
transAllocator :: Allocator -> Result
transAllocator x = case x of
  Allocator1 subtypeindication -> failure x
  Allocator2 qualifiedexpression -> failure x
transQualified_expression :: Qualified_expression -> Result
transQualified_expression x = case x of
  Qualified_expression expression -> failure x
  Qualified_expression1 typemark expression -> failure x
  Qualified_expression2 typemark aggregate -> failure x
transArchitecture_body :: Architecture_body -> Result
transArchitecture_body x = case x of
  Architecture_body identifier entityname architecturedeclarativepart architecturestatementpart maybearch maybearchitecturesimplename -> failure x
transMaybeArch :: MaybeArch -> Result
transMaybeArch x = case x of
  MaybeArch_ARCHITECTURE -> failure x
  MaybeArch1 -> failure x
transMaybeArchitecture_simple_name :: MaybeArchitecture_simple_name -> Result
transMaybeArchitecture_simple_name x = case x of
  MaybeArchitecture_simple_nameArchitecture_simple_name architecturesimplename -> failure x
  MaybeArchitecture_simple_name1 -> failure x
transArchitecture_simple_name :: Architecture_simple_name -> Result
transArchitecture_simple_name x = case x of
  Architecture_simple_name simplename -> failure x
transArray_type_definition :: Array_type_definition -> Result
transArray_type_definition x = case x of
  Array_type_definitionUnconstrained_array_definition unconstrainedarraydefinition -> failure x
  Array_type_definitionConstrained_array_definition constrainedarraydefinition -> failure x
transAssertion :: Assertion -> Result
transAssertion x = case x of
  Assertion condition maybereports maybeseveritys -> failure x
transAssertion_statement :: Assertion_statement -> Result
transAssertion_statement x = case x of
  Assertion_statement labels assertion -> failure x
transAssociation_element :: Association_element -> Result
transAssociation_element x = case x of
  Association_element formalparts actualpart -> failure x
transAssociation_list :: Association_list -> Result
transAssociation_list x = case x of
  Association_list associationelements -> failure x
transGeneric_clause_Map :: Generic_clause_Map -> Result
transGeneric_clause_Map x = case x of
  Generic_clause_Map genericclause genericmapaspectsemis -> failure x
transPort_clause_map :: Port_clause_map -> Result
transPort_clause_map x = case x of
  Port_clause_map portclause portmapaspectsemis -> failure x
transPort_map_aspectSemi :: Port_map_aspectSemi -> Result
transPort_map_aspectSemi x = case x of
  Port_map_aspectSemi portmapaspectsemi -> failure x
transIndex_specificationPar :: Index_specificationPar -> Result
transIndex_specificationPar x = case x of
  Index_specificationPar indexspecification -> failure x
transGuard_expressionPar :: Guard_expressionPar -> Result
transGuard_expressionPar x = case x of
  Guard_expressionPar guardexpressionpar -> failure x
transCase_labelColon :: Case_labelColon -> Result
transCase_labelColon x = case x of
  Case_labelColon caselabel -> failure x
transCase_label :: Case_label -> Result
transCase_label x = case x of
  Case_label label -> failure x
transWaveformElse :: WaveformElse -> Result
transWaveformElse x = case x of
  WaveformElse waveform condition -> failure x
  WaveformNoElse whenconditions -> failure x
transWhenCondition :: WhenCondition -> Result
transWhenCondition x = case x of
  WhenCondition condition -> failure x
transDotInt :: DotInt -> Result
transDotInt x = case x of
  DotInt vinteger -> failure x
transStatic_expressionAssign :: Static_expressionAssign -> Result
transStatic_expressionAssign x = case x of
  Static_expressionAssign staticexpression -> failure x
transLoopLabelColon :: LoopLabelColon -> Result
transLoopLabelColon x = case x of
  LoopLabelColon looplabel -> failure x
transLoop_label :: Loop_label -> Result
transLoop_label x = case x of
  Loop_label label -> failure x
transAttribute_declaration :: Attribute_declaration -> Result
transAttribute_declaration x = case x of
  Attribute_declaration identifier typemark -> failure x
transAttribute_designator :: Attribute_designator -> Result
transAttribute_designator x = case x of
  Attribute_designator attributesimplename -> failure x
transAttribute_simple_name :: Attribute_simple_name -> Result
transAttribute_simple_name x = case x of
  Attribute_simple_name simplename -> failure x
transAttribute_name :: Attribute_name -> Result
transAttribute_name x = case x of
  Attribute_name prefix signatures attributedesignator expresspars -> failure x
transExpressPar :: ExpressPar -> Result
transExpressPar x = case x of
  ExpressPar expression -> failure x
transAttribute_specification :: Attribute_specification -> Result
transAttribute_specification x = case x of
  Attribute_specification attributedesignator entityspecification expression -> failure x
transBase :: Base -> Result
transBase x = case x of
  Base vinteger -> failure x
transBase_unit_declaration :: Base_unit_declaration -> Result
transBase_unit_declaration x = case x of
  Base_unit_declaration identifier -> failure x
transBased_integer :: Based_integer -> Result
transBased_integer x = case x of
  Based_integer extendeddigits -> failure x
transDigit :: Digit -> Result
transDigit x = case x of
  Digit_0 -> failure x
  Digit_1 -> failure x
  Digit_2 -> failure x
  Digit_3 -> failure x
  Digit_4 -> failure x
  Digit_5 -> failure x
  Digit_6 -> failure x
  Digit_7 -> failure x
  Digit_8 -> failure x
  Digit_9 -> failure x
transBased_literal :: Based_literal -> Result
transBased_literal x = case x of
  Based_literal base basedintegers exponents -> failure x
transBasic_identifier :: Basic_identifier -> Result
transBasic_identifier x = case x of
  Basic_identifier ident -> failure x
transBinding_indication :: Binding_indication -> Result
transBinding_indication x = case x of
  Binding_indication useentitys genericmapaspects portmapaspects -> failure x
transBit_string_literal :: Bit_string_literal -> Result
transBit_string_literal x = case x of
  Bit_string_literal basespecifier bitvalue -> failure x
transBit_value :: Bit_value -> Result
transBit_value x = case x of
  Bit_value extendeddigits -> failure x
transBlock_configuration :: Block_configuration -> Result
transBlock_configuration x = case x of
  Block_configuration blockspecification useentitys configurationitems -> failure x
transBlock_declarative_item :: Block_declarative_item -> Result
transBlock_declarative_item x = case x of
  Block_declarative_itemSubprogram_declaration subprogramdeclaration -> failure x
  Block_declarative_itemSubprogram_body subprogrambody -> failure x
  Block_declarative_itemType_declaration typedeclaration -> failure x
  Block_declarative_itemSubtype_declaration subtypedeclaration -> failure x
  Block_declarative_itemConstant_declaration constantdeclaration -> failure x
  Block_declarative_itemSignal_declaration signaldeclaration -> failure x
  Block_declarative_itemShared_variable_declaration sharedvariabledeclaration -> failure x
  Block_declarative_itemFile_declaration filedeclaration -> failure x
  Block_declarative_itemAlias_declaration aliasdeclaration -> failure x
  Block_declarative_itemComponent_declaration componentdeclaration -> failure x
  Block_declarative_itemAttribute_declaration attributedeclaration -> failure x
  Block_declarative_itemAttribute_specification attributespecification -> failure x
  Block_declarative_itemConfiguration_specification configurationspecification -> failure x
  Block_declarative_itemDisconnection_specification disconnectionspecification -> failure x
  Block_declarative_itemUse_clause useclause -> failure x
  Block_declarative_itemGroup_template_declaration grouptemplatedeclaration -> failure x
  Block_declarative_itemGroup_declaration groupdeclaration -> failure x
transShared_variable_declaration :: Shared_variable_declaration -> Result
transShared_variable_declaration x = case x of
  Shared_variable_declaration variabledeclaration -> failure x
transBlock_declarative_part :: Block_declarative_part -> Result
transBlock_declarative_part x = case x of
  Block_declarative_part blockdeclarativeitems -> failure x
transBlock_header :: Block_header -> Result
transBlock_header x = case x of
  Block_header genericclausemaps portclausemaps -> failure x
transArchitecture_name :: Architecture_name -> Result
transArchitecture_name x = case x of
  Architecture_name name -> failure x
transGenerate_statement_label :: Generate_statement_label -> Result
transGenerate_statement_label x = case x of
  Generate_statement_label name -> failure x
transBlock_specification :: Block_specification -> Result
transBlock_specification x = case x of
  Block_specificationArchitecture_name architecturename -> failure x
  Block_specificationBlock_statement_label blockstatementlabel -> failure x
  Block_specification1 generatestatementlabel indexspecificationpar -> failure x
transBlock_statement_label :: Block_statement_label -> Result
transBlock_statement_label x = case x of
  Block_statement_label label -> failure x
transBlock_statement :: Block_statement -> Result
transBlock_statement x = case x of
  Block_statement blocklabel guardexpressionpars iss blockheader blockdeclarativepart blockstatementpart blocklabels -> failure x
transBlock_label :: Block_label -> Result
transBlock_label x = case x of
  Block_label label -> failure x
transBlock_statement_part :: Block_statement_part -> Result
transBlock_statement_part x = case x of
  Block_statement_part concurrentstatements -> failure x
transCase_statement :: Case_statement -> Result
transCase_statement x = case x of
  Case_statement caselabelcolons expression casestatementalternatives caselabels -> failure x
transChoice :: Choice -> Result
transChoice x = case x of
  ChoiceSimple_expression simpleexpression -> failure x
  ChoiceDiscrete_range discreterange -> failure x
  ChoiceElement_simple_name elementsimplename -> failure x
  Choice_OTHERS -> failure x
transElement_simple_name :: Element_simple_name -> Result
transElement_simple_name x = case x of
  Element_simple_name simplename -> failure x
transChoices :: Choices -> Result
transChoices x = case x of
  Choices choices -> failure x
transCase_statement_alternative :: Case_statement_alternative -> Result
transCase_statement_alternative x = case x of
  Case_statement_alternative choices sequenceofstatements -> failure x
transCharacter_literal :: Character_literal -> Result
transCharacter_literal x = case x of
  Character_literal graphiccharacter -> failure x
transComponent_configuration :: Component_configuration -> Result
transComponent_configuration x = case x of
  Component_configuration componentspecification bindingindications blockconfigurations -> failure x
transComponent_declaration :: Component_declaration -> Result
transComponent_declaration x = case x of
  Component_declaration identifier iss localgenericclauses localportclauses componentsimplenames -> failure x
transComponent_simple_name :: Component_simple_name -> Result
transComponent_simple_name x = case x of
  Component_simple_name simplename -> failure x
transLocal_port_clause :: Local_port_clause -> Result
transLocal_port_clause x = case x of
  Local_port_clause portclause -> failure x
transComponent_instantiation_statement :: Component_instantiation_statement -> Result
transComponent_instantiation_statement x = case x of
  Component_instantiation_statement instantiationlabel instantiatedunit genericmapaspects portmapaspects -> failure x
transInstantiation_label :: Instantiation_label -> Result
transInstantiation_label x = case x of
  Instantiation_label label -> failure x
transComponent_specification :: Component_specification -> Result
transComponent_specification x = case x of
  Component_specification instantiationlist componentname -> failure x
transComponent_name :: Component_name -> Result
transComponent_name x = case x of
  Component_name name -> failure x
transComposite_type_definition :: Composite_type_definition -> Result
transComposite_type_definition x = case x of
  Composite_type_definitionArray_type_definition arraytypedefinition -> failure x
  Composite_type_definitionRecord_type_definition recordtypedefinition -> failure x
transConcurrent_assertion_statement :: Concurrent_assertion_statement -> Result
transConcurrent_assertion_statement x = case x of
  Concurrent_assertion_statement labels maybepostponeds assertion -> failure x
transMaybePOSTPONED :: MaybePOSTPONED -> Result
transMaybePOSTPONED x = case x of
  MaybePOSTPONED -> failure x
transConcurrent_procedure_call_statement :: Concurrent_procedure_call_statement -> Result
transConcurrent_procedure_call_statement x = case x of
  Concurrent_procedure_call_statement labels maybepostponeds procedurecall -> failure x
transConcurrent_signal_assignment_statement :: Concurrent_signal_assignment_statement -> Result
transConcurrent_signal_assignment_statement x = case x of
  Concurrent_signal_assignment_statement1 labels maybepostponeds conditionalsignalassignment -> failure x
  Concurrent_signal_assignment_statement2 labels maybepostponeds selectedsignalassignment -> failure x
transConcurrent_statement :: Concurrent_statement -> Result
transConcurrent_statement x = case x of
  Concurrent_statementBlock_statement blockstatement -> failure x
  Concurrent_statementProcess_statement processstatement -> failure x
  Concurrent_statementConcurrent_procedure_call_statement concurrentprocedurecallstatement -> failure x
  Concurrent_statementConcurrent_assertion_statement concurrentassertionstatement -> failure x
  Concurrent_statementConcurrent_signal_assignment_statement concurrentsignalassignmentstatement -> failure x
  Concurrent_statementComponent_instantiation_statement componentinstantiationstatement -> failure x
  Concurrent_statementGenerate_statement generatestatement -> failure x
transCondition :: Condition -> Result
transCondition x = case x of
  Condition booleanexpression -> failure x
transBoolean_expression :: Boolean_expression -> Result
transBoolean_expression x = case x of
  Boolean_expression expression -> failure x
transCondition_clause :: Condition_clause -> Result
transCondition_clause x = case x of
  Condition_clause condition -> failure x
transConditional_signal_assignment :: Conditional_signal_assignment -> Result
transConditional_signal_assignment x = case x of
  Conditional_signal_assignment target options conditionalwaveforms -> failure x
transConditional_waveforms :: Conditional_waveforms -> Result
transConditional_waveforms x = case x of
  Conditional_waveforms waveformelses -> failure x
transMaybeCONFIGURATION :: MaybeCONFIGURATION -> Result
transMaybeCONFIGURATION x = case x of
  MaybeCONFIGURATION -> failure x
transConfiguration_declaration :: Configuration_declaration -> Result
transConfiguration_declaration x = case x of
  Configuration_declaration identifier entityname configurationdeclarativepart blockconfiguration maybeconfigurations configurationsimplenames -> failure x
transConfiguration_simple_name :: Configuration_simple_name -> Result
transConfiguration_simple_name x = case x of
  Configuration_simple_name simplename -> failure x
transConfiguration_declarative_item :: Configuration_declarative_item -> Result
transConfiguration_declarative_item x = case x of
  Configuration_declarative_itemUse_clause useclause -> failure x
  Configuration_declarative_itemAttribute_specification attributespecification -> failure x
  Configuration_declarative_itemGroup_declaration groupdeclaration -> failure x
transConfiguration_declarative_part :: Configuration_declarative_part -> Result
transConfiguration_declarative_part x = case x of
  Configuration_declarative_part configurationdeclarativeitems -> failure x
transConfiguration_item :: Configuration_item -> Result
transConfiguration_item x = case x of
  Configuration_itemBlock_configuration blockconfiguration -> failure x
  Configuration_itemComponent_configuration componentconfiguration -> failure x
transConfiguration_specification :: Configuration_specification -> Result
transConfiguration_specification x = case x of
  Configuration_specification componentspecification bindingindication -> failure x
transConstant_declaration :: Constant_declaration -> Result
transConstant_declaration x = case x of
  Constant_declaration identifierlist subtypeindication varassigns -> failure x
transVarAssign :: VarAssign -> Result
transVarAssign x = case x of
  VarAssign expression -> failure x
transConstrained_array_definition :: Constrained_array_definition -> Result
transConstrained_array_definition x = case x of
  Constrained_array_definition indexconstraint elementsubtypeindication -> failure x
transConstraint :: Constraint -> Result
transConstraint x = case x of
  ConstraintRange_constraint rangeconstraint -> failure x
  ConstraintIndex_constraint indexconstraint -> failure x
transContext_clause :: Context_clause -> Result
transContext_clause x = case x of
  Context_clause contextitems -> failure x
transContext_item :: Context_item -> Result
transContext_item x = case x of
  Context_itemLibrary_clause libraryclause -> failure x
  Context_itemUse_clause useclause -> failure x
transDecimal_literal :: Decimal_literal -> Result
transDecimal_literal x = case x of
  Decimal_literal vinteger dotints exponents -> failure x
transDeclaration :: Declaration -> Result
transDeclaration x = case x of
  DeclarationType_declaration typedeclaration -> failure x
  DeclarationSubtype_declaration subtypedeclaration -> failure x
  DeclarationObject_declaration objectdeclaration -> failure x
  DeclarationInterface_declaration interfacedeclaration -> failure x
  DeclarationAlias_declaration aliasdeclaration -> failure x
  DeclarationAttribute_declaration attributedeclaration -> failure x
  DeclarationComponent_declaration componentdeclaration -> failure x
  DeclarationGroup_template_declaration grouptemplatedeclaration -> failure x
  DeclarationGroup_declaration groupdeclaration -> failure x
  DeclarationEntity_declaration entitydeclaration -> failure x
  DeclarationConfiguration_declaration configurationdeclaration -> failure x
  DeclarationSubprogram_declaration subprogramdeclaration -> failure x
  DeclarationPackage_declaration packagedeclaration -> failure x
transDelay_mechanism :: Delay_mechanism -> Result
transDelay_mechanism x = case x of
  Delay_mechanism_TRANSPORT -> failure x
  Delay_mechanism1 mayberejecttimes -> failure x
transMaybeRejectTime :: MaybeRejectTime -> Result
transMaybeRejectTime x = case x of
  MaybeRejectTime timeexpression -> failure x
transDesign_file :: Design_file -> Result
transDesign_file x = case x of
  Design_file designunits -> failure x
transDesign_unit :: Design_unit -> Result
transDesign_unit x = case x of
  Design_unit contextclause libraryunit -> failure x
transDesignator :: Designator -> Result
transDesignator x = case x of
  DesignatorIdentifier identifier -> failure x
  DesignatorOperator_symbol operatorsymbol -> failure x
transDirection :: Direction -> Result
transDirection x = case x of
  Direction_TO -> failure x
  Direction_DOWNTO -> failure x
transDisconnection_specification :: Disconnection_specification -> Result
transDisconnection_specification x = case x of
  Disconnection_specification guardedsignalspecification timeexpression -> failure x
transDiscrete_range :: Discrete_range -> Result
transDiscrete_range x = case x of
  Discrete_rangeDiscrete_subtype_indication discretesubtypeindication -> failure x
  Discrete_rangeRange range -> failure x
transDiscrete_subtype_indication :: Discrete_subtype_indication -> Result
transDiscrete_subtype_indication x = case x of
  Discrete_subtype_indication subprogramdeclarativeitem -> failure x
transElement_declaration :: Element_declaration -> Result
transElement_declaration x = case x of
  Element_declaration identifierlist elementsubtypedefinition -> failure x
transChoiceAssign :: ChoiceAssign -> Result
transChoiceAssign x = case x of
  ChoiceAssign choices -> failure x
transElement_association :: Element_association -> Result
transElement_association x = case x of
  Element_association choiceassigns expression -> failure x
transElement_subtype_definition :: Element_subtype_definition -> Result
transElement_subtype_definition x = case x of
  Element_subtype_definition subtypeindication -> failure x
transEntity_aspect :: Entity_aspect -> Result
transEntity_aspect x = case x of
  Entity_aspect1 entityname pararchitectureidentifiers -> failure x
  Entity_aspect2 configurationname -> failure x
  Entity_aspect_OPEN -> failure x
transConfiguration_name :: Configuration_name -> Result
transConfiguration_name x = case x of
  Configuration_name name -> failure x
transParArchitecture_identifier :: ParArchitecture_identifier -> Result
transParArchitecture_identifier x = case x of
  ParArchitecture_identifier architectureidentifier -> failure x
transUseEntity :: UseEntity -> Result
transUseEntity x = case x of
  UseEntity entityaspect -> failure x
transEntity_class :: Entity_class -> Result
transEntity_class x = case x of
  Entity_class_ENTITY -> failure x
  Entity_class_ARCHITECTURE -> failure x
  Entity_class_CONFIGURATION -> failure x
  Entity_class_PROCEDURE -> failure x
  Entity_class_FUNCTION -> failure x
  Entity_class_PACKAGE -> failure x
  Entity_class_TYPE -> failure x
  Entity_class_SUBTYPE -> failure x
  Entity_class_CONSTANT -> failure x
  Entity_class_SIGNAL -> failure x
  Entity_class_VARIABLE -> failure x
  Entity_class_COMPONENT -> failure x
  Entity_class_LABEL -> failure x
  Entity_class_LITERAL -> failure x
  Entity_class_UNITS -> failure x
  Entity_class_GROUP -> failure x
  Entity_class_FILE -> failure x
transECArrows :: ECArrows -> Result
transECArrows x = case x of
  ECArrows -> failure x
transEntity_class_entry :: Entity_class_entry -> Result
transEntity_class_entry x = case x of
  Entity_class_entry entityclass ecarrowss -> failure x
transEntity_class_entry_list :: Entity_class_entry_list -> Result
transEntity_class_entry_list x = case x of
  Entity_class_entry_list entityclassentrys -> failure x
transEntity_declaration :: Entity_declaration -> Result
transEntity_declaration x = case x of
  Entity_declaration identifier entityheader entitydeclarativepart beginentitystatementparts entitytexts entitysimplenames -> failure x
transBEGINEntity_statement_part :: BEGINEntity_statement_part -> Result
transBEGINEntity_statement_part x = case x of
  BEGINEntity_statement_part entitystatementpart -> failure x
transENTITYText :: ENTITYText -> Result
transENTITYText x = case x of
  ENTITYText entitystatementpart -> failure x
transEntity_simple_name :: Entity_simple_name -> Result
transEntity_simple_name x = case x of
  Entity_simple_name simplename -> failure x
transEntity_declarative_item :: Entity_declarative_item -> Result
transEntity_declarative_item x = case x of
  Entity_declarative_itemSubprogram_declaration subprogramdeclaration -> failure x
  Entity_declarative_itemSubprogram_body subprogrambody -> failure x
  Entity_declarative_itemType_declaration typedeclaration -> failure x
  Entity_declarative_itemSubtype_declaration subtypedeclaration -> failure x
  Entity_declarative_itemConstant_declaration constantdeclaration -> failure x
  Entity_declarative_itemSignal_declaration signaldeclaration -> failure x
  Entity_declarative_itemShared_variable_declaration sharedvariabledeclaration -> failure x
  Entity_declarative_itemFile_declaration filedeclaration -> failure x
  Entity_declarative_itemAlias_declaration aliasdeclaration -> failure x
  Entity_declarative_itemAttribute_declaration attributedeclaration -> failure x
  Entity_declarative_itemAttribute_specification attributespecification -> failure x
  Entity_declarative_itemDisconnection_specification disconnectionspecification -> failure x
  Entity_declarative_itemUse_clause useclause -> failure x
  Entity_declarative_itemGroup_template_declaration grouptemplatedeclaration -> failure x
  Entity_declarative_itemGroup_declaration groupdeclaration -> failure x
transEntity_declarative_part :: Entity_declarative_part -> Result
transEntity_declarative_part x = case x of
  Entity_declarative_part entitydeclarativeitems -> failure x
transEntity_designator :: Entity_designator -> Result
transEntity_designator x = case x of
  Entity_designator entitytag signatures -> failure x
transEntity_header :: Entity_header -> Result
transEntity_header x = case x of
  Entity_header formalgenericclauses formalportclauses -> failure x
transFormal_generic_clause :: Formal_generic_clause -> Result
transFormal_generic_clause x = case x of
  Formal_generic_clause genericclause -> failure x
transFormal_port_clause :: Formal_port_clause -> Result
transFormal_port_clause x = case x of
  Formal_port_clause portclause -> failure x
transEntity_name_list :: Entity_name_list -> Result
transEntity_name_list x = case x of
  Entity_name_list1 entitydesignators -> failure x
  Entity_name_list_OTHERS -> failure x
  Entity_name_list_ALL -> failure x
transEntity_specification :: Entity_specification -> Result
transEntity_specification x = case x of
  Entity_specification entitynamelist entityclass -> failure x
transEntity_statement :: Entity_statement -> Result
transEntity_statement x = case x of
  Entity_statementConcurrent_assertion_statement concurrentassertionstatement -> failure x
  Entity_statementPassive_concurrent_procedure_call_statement passiveconcurrentprocedurecallstatement -> failure x
  Entity_statementPassive_process_statement passiveprocessstatement -> failure x
transPassive_process_statement :: Passive_process_statement -> Result
transPassive_process_statement x = case x of
  Passive_process_statement processstatement -> failure x
transPassive_concurrent_procedure_call_statement :: Passive_concurrent_procedure_call_statement -> Result
transPassive_concurrent_procedure_call_statement x = case x of
  Passive_concurrent_procedure_call_statement concurrentprocedurecallstatement -> failure x
transEntity_statement_part :: Entity_statement_part -> Result
transEntity_statement_part x = case x of
  Entity_statement_part entitystatements -> failure x
transEntity_tag :: Entity_tag -> Result
transEntity_tag x = case x of
  Entity_tagSimple_name simplename -> failure x
  Entity_tagCharacter_literal characterliteral -> failure x
  Entity_tagOperator_symbol operatorsymbol -> failure x
transEnumeration_literal :: Enumeration_literal -> Result
transEnumeration_literal x = case x of
  Enumeration_literalIdentifier identifier -> failure x
  Enumeration_literalCharacter_literal characterliteral -> failure x
transEnumeration_type_definition :: Enumeration_type_definition -> Result
transEnumeration_type_definition x = case x of
  Enumeration_type_definition enumerationliterals -> failure x
transExit_statement :: Exit_statement -> Result
transExit_statement x = case x of
  Exit_statement labels looplabels whenconditions -> failure x
transExponent :: Exponent -> Result
transExponent x = case x of
  Exponent1 plusop vinteger -> failure x
  Exponent2 vinteger -> failure x
transPlusOp :: PlusOp -> Result
transPlusOp x = case x of
  PlusOp -> failure x
transExpression :: Expression -> Result
transExpression x = case x of
  Expression1 relation1 expops relation2 -> failure x
  ExpressionRelation relation -> failure x
transExpOps :: ExpOps -> Result
transExpOps x = case x of
  ExpOps_AND -> failure x
  ExpOps_OR -> failure x
  ExpOps_XOR -> failure x
  ExpOps_NAND -> failure x
  ExpOps_NOR -> failure x
  ExpOps_XNOR -> failure x
transExtended_digit :: Extended_digit -> Result
transExtended_digit x = case x of
  Extended_digitDigit digit -> failure x
  Extended_digitLetter letter -> failure x
transExtended_identifier :: Extended_identifier -> Result
transExtended_identifier x = case x of
  Extended_identifier graphiccharacters -> failure x
transFactor :: Factor -> Result
transFactor x = case x of
  Factor1 primarys -> failure x
  Factor2 primary -> failure x
  Factor3 primary -> failure x
transFile_declaration :: File_declaration -> Result
transFile_declaration x = case x of
  File_declaration filematchs -> failure x
transFileMatch :: FileMatch -> Result
transFileMatch x = case x of
  FileMatch identifierlist subtypeindication fileopeninformation -> failure x
transFile_logical_name :: File_logical_name -> Result
transFile_logical_name x = case x of
  File_logical_name stringexpression -> failure x
transString_expression :: String_expression -> Result
transString_expression x = case x of
  String_expression expression -> failure x
transFile_open_information :: File_open_information -> Result
transFile_open_information x = case x of
  File_open_information openfiles filelogicalname -> failure x
transOPENFile :: OPENFile -> Result
transOPENFile x = case x of
  OPENFile fileopenkindexpression -> failure x
transFile_open_kind_expression :: File_open_kind_expression -> Result
transFile_open_kind_expression x = case x of
  File_open_kind_expression expression -> failure x
transFile_type_definition :: File_type_definition -> Result
transFile_type_definition x = case x of
  File_type_definition typemark -> failure x
transFloating_type_definition :: Floating_type_definition -> Result
transFloating_type_definition x = case x of
  Floating_type_definition rangeconstraint -> failure x
transFormal_designator :: Formal_designator -> Result
transFormal_designator x = case x of
  Formal_designatorGeneric_name genericname -> failure x
  Formal_designatorPort_name portname -> failure x
  Formal_designatorParameter_name parametername -> failure x
transGeneric_name :: Generic_name -> Result
transGeneric_name x = case x of
  Generic_name name -> failure x
transPort_name :: Port_name -> Result
transPort_name x = case x of
  Port_name name -> failure x
transParameter_name :: Parameter_name -> Result
transParameter_name x = case x of
  Parameter_name name -> failure x
transFormal_parameter_list :: Formal_parameter_list -> Result
transFormal_parameter_list x = case x of
  Formal_parameter_list parameterinterfacelist -> failure x
transParameter_interface_list :: Parameter_interface_list -> Result
transParameter_interface_list x = case x of
  Parameter_interface_list interfacelist -> failure x
transFormal_part :: Formal_part -> Result
transFormal_part x = case x of
  Formal_partFormal_designator formaldesignator -> failure x
  Formal_part1 functionname formaldesignator -> failure x
  Formal_part2 typemark formaldesignator -> failure x
transFunction_name :: Function_name -> Result
transFunction_name x = case x of
  Function_name name -> failure x
transFull_type_declaration :: Full_type_declaration -> Result
transFull_type_declaration x = case x of
  Full_type_declaration identifier typedefinition -> failure x
transFunction_call :: Function_call -> Result
transFunction_call x = case x of
  Function_call functionname actualparameterpartpars -> failure x
transActual_parameter_partPar :: Actual_parameter_partPar -> Result
transActual_parameter_partPar x = case x of
  Actual_parameter_partPar actualparameterpart -> failure x
transBEGINBlock_declarative_item :: BEGINBlock_declarative_item -> Result
transBEGINBlock_declarative_item x = case x of
  BEGINBlock_declarative_item blockdeclarativeitems -> failure x
transGenerate_statement :: Generate_statement -> Result
transGenerate_statement x = case x of
  Generate_statement generatelabel generationscheme beginblockdeclarativeitems concurrentstatements generatelabels -> failure x
transGenerate_label :: Generate_label -> Result
transGenerate_label x = case x of
  Generate_label label -> failure x
transGeneration_scheme :: Generation_scheme -> Result
transGeneration_scheme x = case x of
  Generation_scheme1 generateparameterspecification -> failure x
  Generation_scheme2 condition -> failure x
transGenerate_parameter_specification :: Generate_parameter_specification -> Result
transGenerate_parameter_specification x = case x of
  Generate_parameter_specification parameterspecification -> failure x
transGeneric_clause :: Generic_clause -> Result
transGeneric_clause x = case x of
  Generic_clause genericlist -> failure x
transGeneric_list :: Generic_list -> Result
transGeneric_list x = case x of
  Generic_list genericinterfacelist -> failure x
transGeneric_interface_list :: Generic_interface_list -> Result
transGeneric_interface_list x = case x of
  Generic_interface_list interfacelist -> failure x
transGeneric_map_aspect :: Generic_map_aspect -> Result
transGeneric_map_aspect x = case x of
  Generic_map_aspect genericassociationlist -> failure x
transGeneric_association_list :: Generic_association_list -> Result
transGeneric_association_list x = case x of
  Generic_association_list associationlist -> failure x
transGeneric_map_aspectSemi :: Generic_map_aspectSemi -> Result
transGeneric_map_aspectSemi x = case x of
  Generic_map_aspectSemi genericmapaspect -> failure x
transGraphic_character :: Graphic_character -> Result
transGraphic_character x = case x of
  Graphic_characterBasic_graphic_character basicgraphiccharacter -> failure x
  Graphic_characterLower_case_letter lowercaseletter -> failure x
  Graphic_characterOther_special_character otherspecialcharacter -> failure x
transOther_special_character :: Other_special_character -> Result
transOther_special_character x = case x of
  Other_special_character -> failure x
transGroup_constituent :: Group_constituent -> Result
transGroup_constituent x = case x of
  Group_constituentName name -> failure x
  Group_constituentCharacter_literal characterliteral -> failure x
transGroup_constituent_list :: Group_constituent_list -> Result
transGroup_constituent_list x = case x of
  Group_constituent_list groupconstituents -> failure x
transGroup_template_declaration :: Group_template_declaration -> Result
transGroup_template_declaration x = case x of
  Group_template_declaration identifier entityclassentrylist -> failure x
transGroup_declaration :: Group_declaration -> Result
transGroup_declaration x = case x of
  Group_declaration identifier grouptemplatename groupconstituentlist -> failure x
transGroup_template_name :: Group_template_name -> Result
transGroup_template_name x = case x of
  Group_template_name name -> failure x
transGuarded_signal_specification :: Guarded_signal_specification -> Result
transGuarded_signal_specification x = case x of
  Guarded_signal_specification guardedsignallist typemark -> failure x
transGuarded_signal_list :: Guarded_signal_list -> Result
transGuarded_signal_list x = case x of
  Guarded_signal_list signallist -> failure x
transIdentifier :: Identifier -> Result
transIdentifier x = case x of
  IdentifierBasic_identifier basicidentifier -> failure x
  IdentifierExtended_identifier extendedidentifier -> failure x
transIdentifier_list :: Identifier_list -> Result
transIdentifier_list x = case x of
  Identifier_list identifiers -> failure x
transIf_statement :: If_statement -> Result
transIf_statement x = case x of
  If_statement iflabelcolons condition sequenceofstatements elsestatements elseifstatements iflabels -> failure x
transIf_labelColon :: If_labelColon -> Result
transIf_labelColon x = case x of
  If_labelColon iflabel -> failure x
transELSEIFStatement :: ELSEIFStatement -> Result
transELSEIFStatement x = case x of
  ELSEIFStatement condition sequenceofstatements -> failure x
transELSEStatement :: ELSEStatement -> Result
transELSEStatement x = case x of
  ELSEStatement sequenceofstatements -> failure x
transIf_label :: If_label -> Result
transIf_label x = case x of
  If_label label -> failure x
transIncomplete_type_declaration :: Incomplete_type_declaration -> Result
transIncomplete_type_declaration x = case x of
  Incomplete_type_declaration identifier -> failure x
transIndex_constraint :: Index_constraint -> Result
transIndex_constraint x = case x of
  Index_constraint discreteranges -> failure x
transIndex_specification :: Index_specification -> Result
transIndex_specification x = case x of
  Index_specificationDiscrete_range discreterange -> failure x
  Index_specificationStatic_expression staticexpression -> failure x
transStatic_expression :: Static_expression -> Result
transStatic_expression x = case x of
  Static_expression expression -> failure x
transIndex_subtype_definition :: Index_subtype_definition -> Result
transIndex_subtype_definition x = case x of
  Index_subtype_definition typemark range -> failure x
transIndexed_name :: Indexed_name -> Result
transIndexed_name x = case x of
  Indexed_name prefix expressions -> failure x
transInstantiated_unit :: Instantiated_unit -> Result
transInstantiated_unit x = case x of
  Instantiated_unit1 componenttexts componentname -> failure x
  Instantiated_unit2 entityname architectureidentifierpars -> failure x
  Instantiated_unit3 configurationname -> failure x
transCOMPONENTText :: COMPONENTText -> Result
transCOMPONENTText x = case x of
  COMPONENTText -> failure x
transArchitecture_identifierPar :: Architecture_identifierPar -> Result
transArchitecture_identifierPar x = case x of
  Architecture_identifierPar architectureidentifier -> failure x
transEntity_name :: Entity_name -> Result
transEntity_name x = case x of
  Entity_name name -> failure x
transArchitecture_identifier :: Architecture_identifier -> Result
transArchitecture_identifier x = case x of
  Architecture_identifier identifier -> failure x
transInstantiation_list :: Instantiation_list -> Result
transInstantiation_list x = case x of
  Instantiation_list1 instantiationlabels -> failure x
  Instantiation_list_OTHERS -> failure x
  Instantiation_list_ALL -> failure x
transVInteger :: VInteger -> Result
transVInteger x = case x of
  VInteger numstring -> failure x
transIntAccuum :: IntAccuum -> Result
transIntAccuum x = case x of
  IntAccuum1 digit intaccuum -> failure x
  IntAccuum2 digit underline intaccuum -> failure x
  IntAccuumDigit digit -> failure x
transUnderline :: Underline -> Result
transUnderline x = case x of
  Underline -> failure x
transInteger_type_definition :: Integer_type_definition -> Result
transInteger_type_definition x = case x of
  Integer_type_definition rangeconstraint -> failure x
transInterface_constant_declaration :: Interface_constant_declaration -> Result
transInterface_constant_declaration x = case x of
  Interface_constant_declaration constanttexts identifierlist intexts subtypeindication staticexpressionassigns -> failure x
transInterface_declaration :: Interface_declaration -> Result
transInterface_declaration x = case x of
  Interface_declarationInterface_constant_declaration interfaceconstantdeclaration -> failure x
  Interface_declarationInterface_signal_declaration interfacesignaldeclaration -> failure x
  Interface_declarationInterface_variable_declaration interfacevariabledeclaration -> failure x
  Interface_declarationInterface_file_declaration interfacefiledeclaration -> failure x
transInterface_element :: Interface_element -> Result
transInterface_element x = case x of
  Interface_element interfacedeclaration -> failure x
transInterface_file_declaration :: Interface_file_declaration -> Result
transInterface_file_declaration x = case x of
  Interface_file_declaration identifierlist subtypeindication -> failure x
transInterface_list :: Interface_list -> Result
transInterface_list x = case x of
  Interface_list interfaceelements -> failure x
transInterface_signal_declaration :: Interface_signal_declaration -> Result
transInterface_signal_declaration x = case x of
  Interface_signal_declaration signaltexts identifierlist modes subtypeindication bustexts staticexpressionassigns -> failure x
transInterface_variable_declaration :: Interface_variable_declaration -> Result
transInterface_variable_declaration x = case x of
  Interface_variable_declaration variabletexts identifierlist modes subtypeindication staticexpressionassigns -> failure x
transIteration_scheme :: Iteration_scheme -> Result
transIteration_scheme x = case x of
  Iteration_scheme1 condition -> failure x
  Iteration_scheme2 loopparameterspecification -> failure x
transLoop_parameter_specification :: Loop_parameter_specification -> Result
transLoop_parameter_specification x = case x of
  Loop_parameter_specification parameterspecification -> failure x
transLabel :: Label -> Result
transLabel x = case x of
  Label identifier -> failure x
transLetter :: Letter -> Result
transLetter x = case x of
  LetterUpper_case_letter uppercaseletter -> failure x
  LetterLower_case_letter lowercaseletter -> failure x
transUpper_case_letter :: Upper_case_letter -> Result
transUpper_case_letter x = case x of
  Upper_case_letter_A -> failure x
  Upper_case_letter_B -> failure x
  Upper_case_letter_C -> failure x
  Upper_case_letter_D -> failure x
  Upper_case_letter_E -> failure x
  Upper_case_letter_F -> failure x
  Upper_case_letter_G -> failure x
  Upper_case_letter_H -> failure x
  Upper_case_letter_I -> failure x
  Upper_case_letter_J -> failure x
  Upper_case_letter_K -> failure x
  Upper_case_letter_L -> failure x
  Upper_case_letter_M -> failure x
  Upper_case_letter_N -> failure x
  Upper_case_letter_O -> failure x
  Upper_case_letter_P -> failure x
  Upper_case_letter_Q -> failure x
  Upper_case_letter_R -> failure x
  Upper_case_letter_S -> failure x
  Upper_case_letter_T -> failure x
  Upper_case_letter_U -> failure x
  Upper_case_letter_V -> failure x
  Upper_case_letter_W -> failure x
  Upper_case_letter_X -> failure x
  Upper_case_letter_Y -> failure x
  Upper_case_letter_Z -> failure x
transLower_case_letter :: Lower_case_letter -> Result
transLower_case_letter x = case x of
  Lower_case_letter_a -> failure x
  Lower_case_letter_b -> failure x
  Lower_case_letter_c -> failure x
  Lower_case_letter_d -> failure x
  Lower_case_letter_e -> failure x
  Lower_case_letter_f -> failure x
  Lower_case_letter_g -> failure x
  Lower_case_letter_h -> failure x
  Lower_case_letter_i -> failure x
  Lower_case_letter_j -> failure x
  Lower_case_letter_k -> failure x
  Lower_case_letter_l -> failure x
  Lower_case_letter_m -> failure x
  Lower_case_letter_n -> failure x
  Lower_case_letter_o -> failure x
  Lower_case_letter_p -> failure x
  Lower_case_letter_q -> failure x
  Lower_case_letter_r -> failure x
  Lower_case_letter_s -> failure x
  Lower_case_letter_t -> failure x
  Lower_case_letter_u -> failure x
  Lower_case_letter_v -> failure x
  Lower_case_letter_w -> failure x
  Lower_case_letter_x -> failure x
  Lower_case_letter_y -> failure x
  Lower_case_letter_z -> failure x
transLetter_or_digit :: Letter_or_digit -> Result
transLetter_or_digit x = case x of
  Letter_or_digitLetter letter -> failure x
  Letter_or_digitDigit digit -> failure x
transLibrary_clause :: Library_clause -> Result
transLibrary_clause x = case x of
  Library_clause logicalnamelist -> failure x
transLibrary_unit :: Library_unit -> Result
transLibrary_unit x = case x of
  Library_unitPrimary_unit primaryunit -> failure x
  Library_unitSecondary_unit secondaryunit -> failure x
transLiteral :: Literal -> Result
transLiteral x = case x of
  LiteralNumeric_literal numericliteral -> failure x
  LiteralEnumeration_literal enumerationliteral -> failure x
  LiteralString_literal stringliteral -> failure x
  LiteralBit_string_literal bitstringliteral -> failure x
  Literal_NULL -> failure x
transLogical_name :: Logical_name -> Result
transLogical_name x = case x of
  Logical_name identifier -> failure x
transLogical_name_list :: Logical_name_list -> Result
transLogical_name_list x = case x of
  Logical_name_list logicalnames -> failure x
transLogical_operator :: Logical_operator -> Result
transLogical_operator x = case x of
  Logical_operator_AND -> failure x
  Logical_operator_OR -> failure x
  Logical_operator_NAND -> failure x
  Logical_operator_NOR -> failure x
  Logical_operator_XOR -> failure x
  Logical_operator_XNOR -> failure x
transLoop_statement :: Loop_statement -> Result
transLoop_statement x = case x of
  Loop_statement looplabelcolons iterationschemes sequenceofstatements looplabels -> failure x
transMiscellaneous_operator :: Miscellaneous_operator -> Result
transMiscellaneous_operator x = case x of
  Miscellaneous_operator1 -> failure x
  Miscellaneous_operator_ABS -> failure x
  Miscellaneous_operator_NOT -> failure x
transMode :: Mode -> Result
transMode x = case x of
  Mode_IN -> failure x
  Mode_OUT -> failure x
  Mode_INOUT -> failure x
  Mode_BUFFER -> failure x
  Mode_LINKAGE -> failure x
transMultiplying_operator :: Multiplying_operator -> Result
transMultiplying_operator x = case x of
  Multiplying_operator1 -> failure x
  Multiplying_operator2 -> failure x
  Multiplying_operator_MOD -> failure x
  Multiplying_operator_REM -> failure x
transName :: Name -> Result
transName x = case x of
  NameSimple_name simplename -> failure x
  NameOperator_symbol operatorsymbol -> failure x
  NameSelected_name selectedname -> failure x
  NameIndexed_name indexedname -> failure x
  NameSlice_name slicename -> failure x
  NameAttribute_name attributename -> failure x
transNext_statement :: Next_statement -> Result
transNext_statement x = case x of
  Next_statement labels looplabels whenconditions -> failure x
transNull_statement :: Null_statement -> Result
transNull_statement x = case x of
  Null_statement labels -> failure x
transNumeric_literal :: Numeric_literal -> Result
transNumeric_literal x = case x of
  Numeric_literalAbstract_literal abstractliteral -> failure x
  Numeric_literalPhysical_literal physicalliteral -> failure x
transObject_declaration :: Object_declaration -> Result
transObject_declaration x = case x of
  Object_declarationConstant_declaration constantdeclaration -> failure x
  Object_declarationSignal_declaration signaldeclaration -> failure x
  Object_declarationVariable_declaration variabledeclaration -> failure x
  Object_declarationFile_declaration filedeclaration -> failure x
transOperator_symbol :: Operator_symbol -> Result
transOperator_symbol x = case x of
  Operator_symbol stringliteral -> failure x
transOptions :: Options -> Result
transOptions x = case x of
  Options guardedtexts delaymechanisms -> failure x
transPackage_body :: Package_body -> Result
transPackage_body x = case x of
  Package_body packagesimplename packagebodydeclarativepart packagebodytexts1 packagebodytexts2 -> failure x
transPackage_simple_name :: Package_simple_name -> Result
transPackage_simple_name x = case x of
  Package_simple_name simplename -> failure x
transPackage_body_declarative_item :: Package_body_declarative_item -> Result
transPackage_body_declarative_item x = case x of
  Package_body_declarative_itemSubprogram_declaration subprogramdeclaration -> failure x
  Package_body_declarative_itemSubprogram_body subprogrambody -> failure x
  Package_body_declarative_itemType_declaration typedeclaration -> failure x
  Package_body_declarative_itemSubtype_declaration subtypedeclaration -> failure x
  Package_body_declarative_itemConstant_declaration constantdeclaration -> failure x
  Package_body_declarative_itemShared_variable_declaration sharedvariabledeclaration -> failure x
  Package_body_declarative_itemFile_declaration filedeclaration -> failure x
  Package_body_declarative_itemAlias_declaration aliasdeclaration -> failure x
  Package_body_declarative_itemUse_clause useclause -> failure x
  Package_body_declarative_itemGroup_template_declaration grouptemplatedeclaration -> failure x
  Package_body_declarative_itemGroup_declaration groupdeclaration -> failure x
transPackage_body_declarative_part :: Package_body_declarative_part -> Result
transPackage_body_declarative_part x = case x of
  Package_body_declarative_part packagebodydeclarativeitems -> failure x
transPackage_declaration :: Package_declaration -> Result
transPackage_declaration x = case x of
  Package_declaration identifier packagedeclarativepart packagetexts packagesimplenames -> failure x
transPackagetext :: Packagetext -> Result
transPackagetext x = case x of
  Packagetext -> failure x
transPackage_declarative_item :: Package_declarative_item -> Result
transPackage_declarative_item x = case x of
  Package_declarative_itemSubprogram_declaration subprogramdeclaration -> failure x
  Package_declarative_itemType_declaration typedeclaration -> failure x
  Package_declarative_itemSubtype_declaration subtypedeclaration -> failure x
  Package_declarative_itemConstant_declaration constantdeclaration -> failure x
  Package_declarative_itemSignal_declaration signaldeclaration -> failure x
  Package_declarative_itemShared_variable_declaration sharedvariabledeclaration -> failure x
  Package_declarative_itemFile_declaration filedeclaration -> failure x
  Package_declarative_itemAlias_declaration aliasdeclaration -> failure x
  Package_declarative_itemComponent_declaration componentdeclaration -> failure x
  Package_declarative_itemAttribute_declaration attributedeclaration -> failure x
  Package_declarative_itemAttribute_specification attributespecification -> failure x
  Package_declarative_itemDisconnection_specification disconnectionspecification -> failure x
  Package_declarative_itemUse_clause useclause -> failure x
  Package_declarative_itemGroup_template_declaration grouptemplatedeclaration -> failure x
  Package_declarative_itemGroup_declaration groupdeclaration -> failure x
transPackage_declarative_part :: Package_declarative_part -> Result
transPackage_declarative_part x = case x of
  Package_declarative_part packagedeclarativeitems -> failure x
transParameter_specification :: Parameter_specification -> Result
transParameter_specification x = case x of
  Parameter_specification identifier discreterange -> failure x
transPhysical_literal :: Physical_literal -> Result
transPhysical_literal x = case x of
  Physical_literal abstractliterals unitname -> failure x
transUnit_name :: Unit_name -> Result
transUnit_name x = case x of
  Unit_name name -> failure x
transPhysical_type_definition :: Physical_type_definition -> Result
transPhysical_type_definition x = case x of
  Physical_type_definition rangeconstraint baseunitdeclaration secondaryunitdeclarations physicaltypesimplenames -> failure x
transPhysical_type_simple_name :: Physical_type_simple_name -> Result
transPhysical_type_simple_name x = case x of
  Physical_type_simple_name simplename -> failure x
transPort_clause :: Port_clause -> Result
transPort_clause x = case x of
  Port_clause portlist -> failure x
transPort_list :: Port_list -> Result
transPort_list x = case x of
  Port_list portinterfacelist -> failure x
transPort_interface_list :: Port_interface_list -> Result
transPort_interface_list x = case x of
  Port_interface_list interfacelist -> failure x
transPort_map_aspect :: Port_map_aspect -> Result
transPort_map_aspect x = case x of
  Port_map_aspect portassociationlist -> failure x
transPort_association_list :: Port_association_list -> Result
transPort_association_list x = case x of
  Port_association_list associationlist -> failure x
transProcedure_name :: Procedure_name -> Result
transProcedure_name x = case x of
  Procedure_name name -> failure x
transPrefix :: Prefix -> Result
transPrefix x = case x of
  PrefixName name -> failure x
  PrefixFunction_call functioncall -> failure x
transPrimary :: Primary -> Result
transPrimary x = case x of
  PrimaryName name -> failure x
  PrimaryLiteral literal -> failure x
  PrimaryAggregate aggregate -> failure x
  PrimaryFunction_call functioncall -> failure x
  PrimaryQualified_expression qualifiedexpression -> failure x
  PrimaryType_conversion typeconversion -> failure x
  PrimaryAllocator allocator -> failure x
  Primary1 expression -> failure x
transPrimary_unit :: Primary_unit -> Result
transPrimary_unit x = case x of
  Primary_unitEntity_declaration entitydeclaration -> failure x
  Primary_unitConfiguration_declaration configurationdeclaration -> failure x
  Primary_unitPackage_declaration packagedeclaration -> failure x
transProcedure_call :: Procedure_call -> Result
transProcedure_call x = case x of
  Procedure_call1 procedurename actualparameterpartpars -> failure x
transProcedure_call_statement :: Procedure_call_statement -> Result
transProcedure_call_statement x = case x of
  Procedure_call_statement labels procedurecall -> failure x
transProcess_declarative_item :: Process_declarative_item -> Result
transProcess_declarative_item x = case x of
  Process_declarative_itemSubprogram_declaration subprogramdeclaration -> failure x
  Process_declarative_itemSubprogram_body subprogrambody -> failure x
  Process_declarative_itemType_declaration typedeclaration -> failure x
  Process_declarative_itemSubtype_declaration subtypedeclaration -> failure x
  Process_declarative_itemConstant_declaration constantdeclaration -> failure x
  Process_declarative_itemVariable_declaration variabledeclaration -> failure x
  Process_declarative_itemFile_declaration filedeclaration -> failure x
  Process_declarative_itemAlias_declaration aliasdeclaration -> failure x
  Process_declarative_itemAttribute_declaration attributedeclaration -> failure x
  Process_declarative_itemAttribute_specification attributespecification -> failure x
  Process_declarative_itemUse_clause useclause -> failure x
  Process_declarative_itemGroup_template_declaration grouptemplatedeclaration -> failure x
  Process_declarative_itemGroup_declaration groupdeclaration -> failure x
transProcess_declarative_part :: Process_declarative_part -> Result
transProcess_declarative_part x = case x of
  Process_declarative_part processdeclarativeitems -> failure x
transProcess_statement :: Process_statement -> Result
transProcess_statement x = case x of
  Process_statement processlabelcolons maybepostponeds1 sensitivitylistpars iss processdeclarativepart processstatementpart maybepostponeds2 processlabels -> failure x
transProcess_labelColon :: Process_labelColon -> Result
transProcess_labelColon x = case x of
  Process_labelColon -> failure x
transSensitivity_listPar :: Sensitivity_listPar -> Result
transSensitivity_listPar x = case x of
  Sensitivity_listPar sensitivitylist -> failure x
transProcess_label :: Process_label -> Result
transProcess_label x = case x of
  Process_label label -> failure x
transProcess_statement_part :: Process_statement_part -> Result
transProcess_statement_part x = case x of
  Process_statement_part sensitivitylists -> failure x
transRange :: Range -> Result
transRange x = case x of
  RangeRange_attribute_name rangeattributename -> failure x
  Range1 simpleexpression1 direction simpleexpression2 -> failure x
transRange_attribute_name :: Range_attribute_name -> Result
transRange_attribute_name x = case x of
  Range_attribute_name attributename -> failure x
transRange_constraint :: Range_constraint -> Result
transRange_constraint x = case x of
  Range_constraint range1 range2 -> failure x
transRecord_type_definition :: Record_type_definition -> Result
transRecord_type_definition x = case x of
  Record_type_definition elementdeclarations recordtypesimplenames -> failure x
transRecord_type_simple_name :: Record_type_simple_name -> Result
transRecord_type_simple_name x = case x of
  Record_type_simple_name simplename -> failure x
transRelation :: Relation -> Result
transRelation x = case x of
  Relation shiftexpression reshifts -> failure x
transReShift :: ReShift -> Result
transReShift x = case x of
  ReShift relationaloperator shiftexpression -> failure x
transRelational_operator :: Relational_operator -> Result
transRelational_operator x = case x of
  Relational_operator1 -> failure x
  Relational_operator2 -> failure x
  Relational_operator3 -> failure x
  Relational_operator4 -> failure x
  Relational_operator5 -> failure x
  Relational_operator6 -> failure x
transReport_statement :: Report_statement -> Result
transReport_statement x = case x of
  Report_statement labels expression sevexps -> failure x
transSevExp :: SevExp -> Result
transSevExp x = case x of
  SevExp expression -> failure x
transReturn_statement :: Return_statement -> Result
transReturn_statement x = case x of
  Return_statement labels expressions -> failure x
transScalar_type_definition :: Scalar_type_definition -> Result
transScalar_type_definition x = case x of
  Scalar_type_definitionEnumeration_type_definition enumerationtypedefinition -> failure x
  Scalar_type_definitionInteger_type_definition integertypedefinition -> failure x
  Scalar_type_definitionFloating_type_definition floatingtypedefinition -> failure x
  Scalar_type_definitionPhysical_type_definition physicaltypedefinition -> failure x
transSecondary_unit :: Secondary_unit -> Result
transSecondary_unit x = case x of
  Secondary_unitArchitecture_body architecturebody -> failure x
  Secondary_unitPackage_body packagebody -> failure x
transSecondary_unit_declaration :: Secondary_unit_declaration -> Result
transSecondary_unit_declaration x = case x of
  Secondary_unit_declaration identifier physicalliteral -> failure x
transSelected_name :: Selected_name -> Result
transSelected_name x = case x of
  Selected_name prefix suffix -> failure x
transSelected_signal_assignment :: Selected_signal_assignment -> Result
transSelected_signal_assignment x = case x of
  Selected_signal_assignment expression target options selectedwaveforms -> failure x
transSelected_waveforms :: Selected_waveforms -> Result
transSelected_waveforms x = case x of
  Selected_waveforms wavechoices -> failure x
transWaveChoice :: WaveChoice -> Result
transWaveChoice x = case x of
  WaveChoice waveform choices -> failure x
transSensitivity_clause :: Sensitivity_clause -> Result
transSensitivity_clause x = case x of
  Sensitivity_clause sensitivitylist -> failure x
transSensitivity_list :: Sensitivity_list -> Result
transSensitivity_list x = case x of
  Sensitivity_list signalnames -> failure x
transSignal_name :: Signal_name -> Result
transSignal_name x = case x of
  Signal_name name -> failure x
transSequence_of_statements :: Sequence_of_statements -> Result
transSequence_of_statements x = case x of
  Sequence_of_statements sequenceofstatementss -> failure x
transSequential_statement :: Sequential_statement -> Result
transSequential_statement x = case x of
  Sequential_statementWait_statement waitstatement -> failure x
  Sequential_statementAssertion_statement assertionstatement -> failure x
  Sequential_statementReport_statement reportstatement -> failure x
  Sequential_statementSignal_assignment_statement signalassignmentstatement -> failure x
  Sequential_statementVariable_assignment_statement variableassignmentstatement -> failure x
  Sequential_statementProcedure_call_statement procedurecallstatement -> failure x
  Sequential_statementIf_statement ifstatement -> failure x
  Sequential_statementCase_statement casestatement -> failure x
  Sequential_statementLoop_statement loopstatement -> failure x
  Sequential_statementNext_statement nextstatement -> failure x
  Sequential_statementExit_statement exitstatement -> failure x
  Sequential_statementReturn_statement returnstatement -> failure x
  Sequential_statementNull_statement nullstatement -> failure x
transShift_expression :: Shift_expression -> Result
transShift_expression x = case x of
  Shift_expression simpleexpression shiftoperatorsimpleexpressiontexts -> failure x
transShift_operatorSimple_expressionText :: Shift_operatorSimple_expressionText -> Result
transShift_operatorSimple_expressionText x = case x of
  Shift_operatorSimple_expressionText shiftoperator simpleexpression -> failure x
transShift_operator :: Shift_operator -> Result
transShift_operator x = case x of
  Shift_operator_SLL -> failure x
  Shift_operator_SRL -> failure x
  Shift_operator_SLA -> failure x
  Shift_operator_SRA -> failure x
  Shift_operator_ROL -> failure x
  Shift_operator_ROR -> failure x
transSign :: Sign -> Result
transSign x = case x of
  Sign1 -> failure x
  Sign2 -> failure x
transSignal_assignment_statement :: Signal_assignment_statement -> Result
transSignal_assignment_statement x = case x of
  Signal_assignment_statement labels target delaymechanisms waveform -> failure x
transSignal_declaration :: Signal_declaration -> Result
transSignal_declaration x = case x of
  Signal_declaration signal identifierlist subtypeindication signalkinds varassigns -> failure x
transSignal :: Signal -> Result
transSignal x = case x of
  Signal -> failure x
transSignal_kind :: Signal_kind -> Result
transSignal_kind x = case x of
  Signal_kind_REGISTER -> failure x
  Signal_kind_BUS -> failure x
transSignal_list :: Signal_list -> Result
transSignal_list x = case x of
  Signal_list1 signalnames -> failure x
  Signal_list_OTHERS -> failure x
  Signal_list_ALL -> failure x
transSignature :: Signature -> Result
transSignature x = case x of
  Signature typeres -> failure x
transReturnType :: ReturnType -> Result
transReturnType x = case x of
  ReturnType typemark -> failure x
transTypeRe :: TypeRe -> Result
transTypeRe x = case x of
  TypeRe typemarks returntypes -> failure x
transSimple_expression :: Simple_expression -> Result
transSimple_expression x = case x of
  Simple_expression signs term addoptems -> failure x
transAddOpTem :: AddOpTem -> Result
transAddOpTem x = case x of
  AddOpTem addingoperator term -> failure x
transSimple_name :: Simple_name -> Result
transSimple_name x = case x of
  Simple_name ident -> failure x
transSlice_name :: Slice_name -> Result
transSlice_name x = case x of
  Slice_name prefix discreterange -> failure x
transString_literal :: String_literal -> Result
transString_literal x = case x of
  String_literal graphiccharacters -> failure x
transSubprogram_body :: Subprogram_body -> Result
transSubprogram_body x = case x of
  Subprogram_body subprogramspecification subprogramdeclarativepart subprogramstatementpart subprogramkinds designators -> failure x
transSubprogram_declaration :: Subprogram_declaration -> Result
transSubprogram_declaration x = case x of
  Subprogram_declaration subprogramspecification -> failure x
transSubprogram_declarative_item :: Subprogram_declarative_item -> Result
transSubprogram_declarative_item x = case x of
  Subprogram_declarative_itemSubprogram_declaration subprogramdeclaration -> failure x
  Subprogram_declarative_itemSubprogram_body subprogrambody -> failure x
  Subprogram_declarative_itemType_declaration typedeclaration -> failure x
  Subprogram_declarative_itemSubtype_declaration subtypedeclaration -> failure x
  Subprogram_declarative_itemConstant_declaration constantdeclaration -> failure x
  Subprogram_declarative_itemVariable_declaration variabledeclaration -> failure x
  Subprogram_declarative_itemFile_declaration filedeclaration -> failure x
  Subprogram_declarative_itemAlias_declaration aliasdeclaration -> failure x
  Subprogram_declarative_itemAttribute_declaration attributedeclaration -> failure x
  Subprogram_declarative_itemAttribute_specification attributespecification -> failure x
  Subprogram_declarative_itemUse_clause useclause -> failure x
  Subprogram_declarative_itemGroup_template_declaration grouptemplatedeclaration -> failure x
  Subprogram_declarative_itemGroup_declaration groupdeclaration -> failure x
transSubprogram_declarative_part :: Subprogram_declarative_part -> Result
transSubprogram_declarative_part x = case x of
  Subprogram_declarative_part subprogramdeclarativeitems -> failure x
transSubprogram_kind :: Subprogram_kind -> Result
transSubprogram_kind x = case x of
  Subprogram_kind_PROCEDURE -> failure x
  Subprogram_kind_FUNCTION -> failure x
transSubprogram_specification :: Subprogram_specification -> Result
transSubprogram_specification x = case x of
  Subprogram_specification1 designator formalparameterlistpars -> failure x
  Subprogram_specification2 pureimpures designator formalparameterlistpars typemark -> failure x
transFormal_parameter_listPar :: Formal_parameter_listPar -> Result
transFormal_parameter_listPar x = case x of
  Formal_parameter_listPar formalparameterlist -> failure x
transPureImpure :: PureImpure -> Result
transPureImpure x = case x of
  PureImpure_PURE -> failure x
  PureImpure_IMPURE -> failure x
transSubprogram_statement_part :: Subprogram_statement_part -> Result
transSubprogram_statement_part x = case x of
  Subprogram_statement_part sequentialstatements -> failure x
transSubtype_declaration :: Subtype_declaration -> Result
transSubtype_declaration x = case x of
  Subtype_declaration identifier subtypeindication -> failure x
transSubtype_indication :: Subtype_indication -> Result
transSubtype_indication x = case x of
  Subtype_indication resolutionfunctionnames typemark constraints -> failure x
transResolution_function_name :: Resolution_function_name -> Result
transResolution_function_name x = case x of
  Resolution_function_name ident -> failure x
transSuffix :: Suffix -> Result
transSuffix x = case x of
  SuffixSimple_name simplename -> failure x
  SuffixCharacter_literal characterliteral -> failure x
  SuffixOperator_symbol operatorsymbol -> failure x
  Suffix_ALL -> failure x
transTarget :: Target -> Result
transTarget x = case x of
  TargetName name -> failure x
  TargetAggregate aggregate -> failure x
transTerm :: Term -> Result
transTerm x = case x of
  Term factor facmulfacs -> failure x
transFacMulFac :: FacMulFac -> Result
transFacMulFac x = case x of
  FacMulFac multiplyingoperator factor -> failure x
transTimeout_clause :: Timeout_clause -> Result
transTimeout_clause x = case x of
  Timeout_clause timeexpression -> failure x
transTime_expression :: Time_expression -> Result
transTime_expression x = case x of
  Time_expression expression -> failure x
transType_conversion :: Type_conversion -> Result
transType_conversion x = case x of
  Type_conversion typemark expression -> failure x
transType_declaration :: Type_declaration -> Result
transType_declaration x = case x of
  Type_declarationFull_type_declaration fulltypedeclaration -> failure x
  Type_declarationIncomplete_type_declaration incompletetypedeclaration -> failure x
transType_definition :: Type_definition -> Result
transType_definition x = case x of
  Type_definitionScalar_type_definition scalartypedefinition -> failure x
  Type_definitionComposite_type_definition compositetypedefinition -> failure x
  Type_definitionAccess_type_definition accesstypedefinition -> failure x
  Type_definitionFile_type_definition filetypedefinition -> failure x
transType_mark :: Type_mark -> Result
transType_mark x = case x of
  Type_markType_name typename -> failure x
  Type_markSubtype_name subtypename -> failure x
transType_name :: Type_name -> Result
transType_name x = case x of
  Type_name ident -> failure x
transUnconstrained_array_definition :: Unconstrained_array_definition -> Result
transUnconstrained_array_definition x = case x of
  Unconstrained_array_definition indexsubtypedefinitions elementsubtypeindication -> failure x
transElement_subtype_indication :: Element_subtype_indication -> Result
transElement_subtype_indication x = case x of
  Element_subtype_indication subtypeindication -> failure x
transSubtype_name :: Subtype_name -> Result
transSubtype_name x = case x of
  Subtype_name ident -> failure x
transUse_clause :: Use_clause -> Result
transUse_clause x = case x of
  Use_clause selectednames -> failure x
transVariable_assignment_statement :: Variable_assignment_statement -> Result
transVariable_assignment_statement x = case x of
  Variable_assignment_statement labels target expression -> failure x
transVariable_declaration :: Variable_declaration -> Result
transVariable_declaration x = case x of
  Variable_declaration sharedtexts identifierlist subtypeindication varassigns -> failure x
transSharedText :: SharedText -> Result
transSharedText x = case x of
  ShareText -> failure x
transValue_expression :: Value_expression -> Result
transValue_expression x = case x of
  Value_expression expression -> failure x
transWait_statement :: Wait_statement -> Result
transWait_statement x = case x of
  Wait_statement labels sensitivityclauses conditionclauses timeoutclauses -> failure x
transWaveform :: Waveform -> Result
transWaveform x = case x of
  Waveform1 waveformelements -> failure x
  Waveform_UNAFFECTED -> failure x
transWaveform_element :: Waveform_element -> Result
transWaveform_element x = case x of
  Waveform_element1 valueexpression aftertimes -> failure x
  Waveform_element2 aftertimes -> failure x
transAfterTime :: AfterTime -> Result
transAfterTime x = case x of
  AfterTime timeexpression -> failure x
transArchitecture_declarative_part :: Architecture_declarative_part -> Result
transArchitecture_declarative_part x = case x of
  Architecture_declarative_part blockdeclarativeitems -> failure x
transArchitecture_statement_part :: Architecture_statement_part -> Result
transArchitecture_statement_part x = case x of
  Architecture_statement_part concurrentstatements -> failure x
transMaybeREPORT :: MaybeREPORT -> Result
transMaybeREPORT x = case x of
  MaybeREPORT1 expression -> failure x
  MaybeREPORT2 -> failure x
transMaybeSEVERITY :: MaybeSEVERITY -> Result
transMaybeSEVERITY x = case x of
  MaybeSEVERITY1 expression -> failure x
  MaybeSEVERITY2 -> failure x
transBase_specifier :: Base_specifier -> Result
transBase_specifier x = case x of
  Base_specifier_B -> failure x
  Base_specifier_O -> failure x
  Base_specifier_X -> failure x
transBasic_character :: Basic_character -> Result
transBasic_character x = case x of
  Basic_characterBasic_graphic_character basicgraphiccharacter -> failure x
  Basic_characterFormat_effector formateffector -> failure x
transFormat_effector :: Format_effector -> Result
transFormat_effector x = case x of
  Format_effector -> failure x
transBasic_graphic_character :: Basic_graphic_character -> Result
transBasic_graphic_character x = case x of
  Basic_graphic_characterUpper_case_letter uppercaseletter -> failure x
  Basic_graphic_characterDigit digit -> failure x
  Basic_graphic_characterSpecial_character specialcharacter -> failure x
  Basic_graphic_characterSpace_character spacecharacter -> failure x
transLocal_generic_clause :: Local_generic_clause -> Result
transLocal_generic_clause x = case x of
  Local_generic_clause genericclause -> failure x
transSpecial_character :: Special_character -> Result
transSpecial_character x = case x of
  Special_character -> failure x
transSpace_character :: Space_character -> Result
transSpace_character x = case x of
  Space_character -> failure x

